// BlueprintGeneratedClass Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C
// Size: 0x30 (Inherited: 0x30)
struct UAres_Characters_FunctionLibrary_C : UBlueprintFunctionLibrary {

	void (struct TArray<struct FHitResult>& Array, struct UObject* , struct FVector , bool , struct UObject* __WorldContext, bool& Success, struct FVector& Location); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x3322a60
	void (struct UObject* WorldContextObject, struct FVector StartLocation, struct FVector , float MaxDistance, bool , struct FVector , struct UObject* __WorldContext, bool& Success, struct FVector& Location); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x3322a60
	void (struct AActor* Actor, struct TSoftClassPtr<UObject> , struct UObject* __WorldContext, struct TArray<struct AActor*>& ); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct AActor* Actor, struct TSoftClassPtr<UObject> , struct UObject* __WorldContext, bool& , struct AActor*& ); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct UStateMachineComponent* StateMachine, struct TArray<struct UStateComponent*>& States, struct UObject* __WorldContext); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x3322a60
	void (struct UEQSStateComponent* EQSStateComponent, struct UObject* __WorldContext); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x3322a60
	void (struct UObject* WorldContextObject, struct FVector Start, struct FVector End, struct TArray<struct AActor*>& ActorsToIgnore, struct UObject* __WorldContext, bool& , struct FHitResult& HitResults); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x3322a60
	void (struct AShooterCharacter* , struct UObject* __WorldContext, struct UAresAbilitySystemComponent*& Component); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	bool (struct AShooterCharacter* InShooterCharacter, struct FVector , struct UObject* __WorldContext); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct TArray<struct FName>& , struct AActor* InActor, struct UObject* __WorldContext, bool& HasTag); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	bool ShooterCharacterIsCurrentViewTarget(struct UObject* InActor, struct UObject* __WorldContext); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C.ShooterCharacterIsCurrentViewTarget // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct FVector SearchOrigin, struct TArray<struct AActor*>& IgnoreActors, float SearchRadius, float OuterRadius, float BaseDamage, float InnerRadius, float MinDamage, struct AController* EventInstigator, struct AActor* DamageCauser, struct UDamageType* DamageTypeClass, enum class EAresRadialCheckType RadialCheckType, enum class EAresLineOfSightCheckType LineOfSightCheck, enum class EAresSearchVisibilityType SearchVisibilityType, struct UObject* Viewer, enum class EAresAlliance Alliance, bool bFindShooterCharacters, bool bFindGameObjects, bool bFindProjectiles, struct UObject* __WorldContext); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x3322a60
	void (struct UObject* WorldContextObject, struct FVector Start, float , bool , bool , struct FVector , struct TArray<struct FName>& IgnoreTags, struct UObject* __WorldContext, bool& , struct FHitResult& Array Element); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct AShooterCharacter* InShooterCharacter, struct FVector InLocation, struct UObject* __WorldContext, float& Distance); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct FVector& SearchOrigin, struct TArray<struct AActor*>& IgnoreActors, float SearchRadius, float AxialOffset, enum class ECollisionChannel TraceChannel, float OuterRadius, float BaseDamage, float InnerRadius, float MinDamage, struct AController* EventInstigator, struct AActor* DamageCauser, struct UDamageType* DamageTypeClass, struct UObject* __WorldContext); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x3322a60
	void (struct FHitResult , struct AActor* WorldContext, float , enum class ETraceTypeQuery TraceChannel, bool TraceComplex, struct TArray<struct AActor*>& ActorsToIgnore, struct UObject* __WorldContext, bool& , struct FVector& , struct FHitResult& ); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x3322a60
	void (enum class ECharacterAbilitySlot , struct UObject* __WorldContext, enum class EAresItemSlot& ItemSlot); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void BuffIsActiveOnActor(struct AActor* InActor, struct UGameplayEffect* , struct UObject* __WorldContext, bool& IsActive); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C.BuffIsActiveOnActor // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct AActor* , int32_t , struct UObject* __WorldContext); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x3322a60
	struct FVector (struct FVector Velocity, struct FHitResult HitResult, float Bounciness, float Friction, struct UObject* __WorldContext); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x3322a60
	bool (struct AShooterCharacter* ShooterCharacter, struct UObject* __WorldContext); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	struct FString (struct AShooterCharacter* InShooterCharacter, struct UObject* __WorldContext); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct UPanelWidget* InWidget, struct UObject* __WorldContext, struct TArray<struct UWidget*>& ); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct UObject* WorldContextObject, struct UUserWidget* WidgetClass, bool TopLevelOnly, struct UObject* __WorldContext); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x3322a60
	void (struct UMeshComponent* , struct AActor* OwningActor, struct UObject* __WorldContext, struct TArray<struct UMaterialInstanceDynamic*>& ); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x3322a60
	void (struct AShooterCharacter* ShooterCharacter, struct UObject* __WorldContext, bool& ); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct AShooterCharacter* ShooterCharacter, struct UObject* __WorldContext, struct APlantedBomb_C*& PlantedBomb); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct AActor* Actor, struct UObject* __WorldContext, struct UCharacterAbilityStatisticsComponent_C*& GameStatisticsComponent, int32_t& CastIndex); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x3322a60
	void AuthAddEffectedPlayerToAbilityCast(struct AActor* , enum class ECharacterAbilityStatisticList Statistic, struct AShooterCharacter* , enum class EAresAlliance Alliance, struct UObject* __WorldContext); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C.AuthAddEffectedPlayerToAbilityCast // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x3322a60
	void AuthAddStatisticToAbilityCast(struct AActor* , struct AShooterCharacter* , enum class ECharacterAbilityStatisticList Statistic, enum class EAresAlliance Alliance, float ValueToAdd, struct UObject* __WorldContext); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C.AuthAddStatisticToAbilityCast // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x3322a60
	void (struct UPrimitiveComponent* PrimitiveComponent, struct UObject* __WorldContext, struct TArray<struct UMaterialInstanceDynamic*>& ); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x3322a60
	void (struct UPrimitiveComponent* PrimitiveComponent, int32_t MaterialIndex, struct UObject* __WorldContext, struct UMaterialInstanceDynamic*& DynamicMaterial); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x3322a60
	void (struct AShooterCharacter* OwningShooterCharacter, enum class EAresItemSlot Slot, enum class ECharacterAbilityStatisticList Statistic, struct AShooterCharacter* , enum class EAresAlliance Alliance, struct UObject* __WorldContext); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x3322a60
	struct UCharacterAbilityStatisticsComponent_C* (struct AShooterCharacter* OwningCharacter, enum class EAresItemSlot Slot, struct UObject* __WorldContext); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x3322a60
	void (struct AShooterCharacter* OwningShooterCharacter, enum class EAresItemSlot Slot, enum class ECharacterAbilityStatisticList Statistic, float ValueToAdd, struct AShooterCharacter* , struct UObject* __WorldContext); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x3322a60
	void (enum class EAresItemSlot ItemSlot, struct AActor* Context, struct FString , struct UObject* __WorldContext, enum class ECharacterAbilitySlot& ); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (enum class EAresItemSlot Slot, struct UObject* __WorldContext, struct FName& ActionMapping); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (enum class EAresItemSlot , struct UObject* __WorldContext, struct FInputChord& , struct FKey& Key, bool& Success); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct FVector Normal, struct UObject* __WorldContext, bool& ); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct UAresAudioComponent* AkComponent, float VolumeMultiplier, float , struct UObject* __WorldContext); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x3322a60
	void (struct AActor* Actor, struct TSoftClassPtr<UObject> , struct UObject* __WorldContext, bool& , struct AActor*& ); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct UPanelWidget* InWidget, struct UObject* __WorldContext, struct TArray<struct UWidget*>& ); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct AAresItem* Target, struct UObject* __WorldContext, struct FInputChord& , struct FKey& Key, bool& Success); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	struct FName (struct AAresItem* Target, struct UObject* __WorldContext); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	bool (struct FName ActionMapping, struct UObject* __WorldContext, struct FInputChord& , struct FKey& Key); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct AShooterCharacter* InShooterCharacter, struct AActor* ActorClass, struct UObject* __WorldContext, struct TArray<struct AActor*>& Actors); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct AShooterCharacter* InShooterCharacter, struct AActor* ActorClass, struct UObject* __WorldContext, bool& ); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct UParticleSystemComponent* , struct FName ParameterName, struct UObject* __WorldContext, float& Value); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct AShooterCharacter* OwningShooterCharacter, enum class EAresItemSlot Slot, struct FName KeyName, float ValueToAdd, enum class EAresAlliance Alliance, struct UObject* __WorldContext); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x3322a60
	void (struct UObject* WorldContextObject, struct UObject* __WorldContext, struct U*& Widget); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x3322a60
	void (struct UObject* __WorldContext, float& NewParam); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct UDamageResponse* , struct UObject* __WorldContext, bool& ); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct FVector StartLocation, struct FVector Normal, struct FVector , float MaxDistance, enum class ETraceTypeQuery Channel, struct UObject* __WorldContext, float& ); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x3322a60
	void (struct FVector Location, struct FVector Normal, struct FVector2D Extents, enum class ETraceTypeQuery Channel, struct UObject* __WorldContext, struct FVector2D& Min, struct FVector2D& Max); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x3322a60
	void (struct UObject* WorldContextObject, struct UObject* __WorldContext, bool& ); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct UParticleSystemComponent* ParticleSystemComponent, struct FVector EndLocation, int32_t LastIndex, struct UObject* __WorldContext); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x3322a60
	void (struct FVector Vector, float Tolerance, struct UObject* __WorldContext, bool& ); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct FVector Vector, struct UObject* __WorldContext, struct FVector& ); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct AActor* Viewer, struct AShooterCharacter* Target, enum class ETraceTypeQuery TraceChannel, struct UObject* __WorldContext, bool& , struct FVector& ); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x3322a60
	void (struct AShooterCharacter* ShooterCharacter, bool , struct UObject* __WorldContext); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x3322a60
	void (struct AAbility_Base_C* AresEquippable, bool , struct UObject* __WorldContext, bool& Success); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x3322a60
	void (struct AShooterCharacter* InShooterCharacter, enum class EAresItemSlot Slot, struct TSoftClassPtr<UObject> , struct UObject* __WorldContext, struct UActorComponent*& ); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct TArray<struct AActor*>& , struct FVector TestLocation, struct UObject* __WorldContext, struct AActor*& , float& ); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x3322a60
	void (struct AActor* InActor, struct TSoftClassPtr<UObject> , struct UObject* __WorldContext, bool& ); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct AActor* InActor, struct UObject* __WorldContext); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x3322a60
	void (struct AActor* InActor, struct AShooterCharacter* , struct UObject* __WorldContext); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x3322a60
	void (struct AActor* InActor, struct AShooterCharacter* , struct AActor* DamageCauser, struct AController* InstigatedByController, struct UObject* __WorldContext); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x3322a60
	void (struct AShooterCharacter* InCharacter, struct TArray<struct FShooterCharacterAndGameplayEffectStruct>& inArray, struct UObject* __WorldContext, bool& Success, struct FActiveGameplayEffectHandle& EffectHandle, int32_t& OutIndex); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct AActor* InActor, struct TArray<struct FActorAnd_FXC_Struct>& inArray, struct UObject* __WorldContext, bool& Success, struct FEffectID& EffectID, int32_t& OutIndex); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct UTimedStateComponent* , struct UObject* __WorldContext, float& ); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct UUserWidget* InWidget, struct UObject* __WorldContext); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x3322a60
	void (struct UUserWidget* , int32_t ZOrder, struct UObject* __WorldContext, struct UUserWidget*& OutWidget); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x3322a60
	void (struct FVector TestLocation, struct FVector ConeOrigin, struct FVector ConeForwardVector, float , struct UObject* __WorldContext, bool& , float& ); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x3322a60
	void (struct AShooterCharacter* OwningShooterCharacter, struct FVector , struct FLinearColor , float , struct FVector2D Size, struct UObject* __WorldContext, struct UWidget*& ); // Function Ares_Characters_FunctionLibrary.Ares_Characters_FunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x3322a60
};

