// BlueprintGeneratedClass TeamCoordinationLibrary.TeamCoordinationLibrary_C
// Size: 0x30 (Inherited: 0x30)
struct UTeamCoordinationLibrary_C : UBlueprintFunctionLibrary {

	struct TArray<struct AActor*> (struct AActor* Source, struct TArray<struct AActor*>& Targets, float , struct UObject* __WorldContext); // Function TeamCoordinationLibrary.TeamCoordinationLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct TArray<struct AActor*>& , struct TArray<struct AActor*>& Targets, float , struct UObject* __WorldContext, struct TArray<int32_t>& ); // Function TeamCoordinationLibrary.TeamCoordinationLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct AActor* Source, struct TArray<struct AActor*>& Targets, float , struct UObject* __WorldContext, struct TArray<int32_t>& ); // Function TeamCoordinationLibrary.TeamCoordinationLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct AActor* Source, struct TArray<struct AActor*>& Targets, struct UObject* __WorldContext, int32_t& ArrayIndex); // Function TeamCoordinationLibrary.TeamCoordinationLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct AActor* Source, struct TArray<struct AActor*>& Targets, struct UObject* __WorldContext, int32_t& ArrayIndex); // Function TeamCoordinationLibrary.TeamCoordinationLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct TArray<struct AActor*>& , struct TArray<struct AActor*>& Targets, struct UObject* __WorldContext, int32_t& ArrayIndex); // Function TeamCoordinationLibrary.TeamCoordinationLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct TArray<struct AShooterPlayerState*>& , bool AliveOnly, struct UObject* __WorldContext, struct TArray<struct AShooterPlayerState*>& ); // Function TeamCoordinationLibrary.TeamCoordinationLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct TArray<struct AShooterPlayerState*>& , bool AliveOnly, struct UObject* __WorldContext, struct TArray<struct AShooterPlayerState*>& ); // Function TeamCoordinationLibrary.TeamCoordinationLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct TArray<struct AShooterPlayerState*>& , bool AliveOnly, struct UObject* __WorldContext, struct TArray<struct AShooterCharacter*>& ); // Function TeamCoordinationLibrary.TeamCoordinationLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct TArray<struct AShooterPlayerState*>& , bool AliveOnly, struct UObject* __WorldContext, struct TArray<struct AShooterCharacter*>& ); // Function TeamCoordinationLibrary.TeamCoordinationLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct TArray<struct AShooterPlayerState*>& , bool AliveOnly, struct UObject* __WorldContext, struct TArray<struct AShooterCharacter*>& ); // Function TeamCoordinationLibrary.TeamCoordinationLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct UBaseTeamComponent* TeamComponent, struct UObject* __WorldContext, struct TArray<struct AShooterPlayerState*>& ShooterPlayerStates); // Function TeamCoordinationLibrary.TeamCoordinationLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
	void (struct UBaseTeamComponent* TeamComponent, struct UObject* __WorldContext, struct TArray<struct AShooterPlayerState*>& ShooterPlayerStates); // Function TeamCoordinationLibrary.TeamCoordinationLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3322a60
};

