// BlueprintGeneratedClass AudBasePawnVOComponent.AudBasePawnVOComponent_C
// Size: 0x9da (Inherited: 0x178)
struct UAudBasePawnVOComponent_C : UBaseVOComponent_C {
	struct FPointerToUberGraphFrame UberGraphFrame; // 0x178(0x08)
	struct TArray<float> EmoteCooldownChargeTimestamps; // 0x180(0x10)
	float EmoteCooldownSeconds; // 0x190(0x04)
	float VO Emote Required Range; // 0x194(0x04)
	float VO Critical Required Range; // 0x198(0x04)
	bool KillStreakAliveCheck; // 0x19c(0x01)
	bool LastManStanding; // 0x19d(0x01)
	char pad_19E[0x2]; // 0x19e(0x02)
	int32_t ClutchPlayRoundNumber; // 0x1a0(0x04)
	char pad_1A4[0x4]; // 0x1a4(0x04)
	struct TMap<enum class MatchVOEnum, struct UAkAudioEvent*> MatchVO; // 0x1a8(0x50)
	struct TMap<enum class CharacterRelationMatchVOEnum, struct FCharacterRelationshipInstance> CharacterSpecificMatchVO; // 0x1f8(0x50)
	struct TMap<enum class MapRelationMatchVOEnum, struct FMapRelationshipInstance> MapSpecificMatchVO; // 0x248(0x50)
	struct TMap<enum class EmoteVOEnum, struct UAkAudioEvent*> EmoteVO; // 0x298(0x50)
	struct TMap<enum class CharacterRelationEmoteVOEnum, struct FCharacterRelationshipInstance> CharacterSpecificEmoteVO; // 0x2e8(0x50)
	struct TMap<enum class RoundStartVOEnum, struct UAkAudioEvent*> RoundStartVO; // 0x338(0x50)
	struct TMap<enum class CharacterRelationRoundStartVOEnum, struct FCharacterRelationshipInstance> CharacterSpecificRoundStartVO; // 0x388(0x50)
	struct TMap<enum class BubbleDownVOEnum, struct UAkAudioEvent*> BubbleDownVO; // 0x3d8(0x50)
	struct TMap<enum class CharacterRelationBubbleDownVOEnum, struct FCharacterRelationshipInstance> CharacterSpecificBubbleDownVO; // 0x428(0x50)
	struct TMap<enum class EffortVOEnum, struct UAkAudioEvent*> EffortVO; // 0x478(0x50)
	struct TMap<enum class TacticalVOEnum, struct UAkAudioEvent*> TacticalVO; // 0x4c8(0x50)
	struct TMap<enum class RoundEndVOEnum, struct UAkAudioEvent*> RoundEndVO; // 0x518(0x50)
	struct TMap<enum class CharacterRelationRoundEndVOEnum, struct FCharacterRelationshipInstance> CharacterSpecificRoundEndVO; // 0x568(0x50)
	struct TMap<enum class KillsVOEnum, struct UAkAudioEvent*> KillsVO; // 0x5b8(0x50)
	struct TMap<enum class CharacterRelationKillsVOEnum, struct FCharacterRelationshipInstance> CharacterSpecificKillVO; // 0x608(0x50)
	struct TMap<enum class AbilitiesVOEnum, struct UAkAudioEvent*> AbilitiesVO; // 0x658(0x50)
	struct TMap<struct UGameplayEffect*, struct UAkAudioEvent*> GameplayEffectKillEvents; // 0x6a8(0x50)
	struct TMap<struct UDamageType*, struct UAkAudioEvent*> DmgTypeKillEvents; // 0x6f8(0x50)
	struct TMap<enum class TagAllianceVOEnum, struct FTagInstance> CharacterTagRoundStartEvents; // 0x748(0x50)
	struct TMap<struct FName, struct UAkAudioEvent*> CharacterTagKillEvents; // 0x798(0x50)
	struct TMap<struct FName, struct UAkAudioEvent*> CharacterTagLastKillEvents; // 0x7e8(0x50)
	struct TMap<enum class CharacterRelationMatchVOEnum, struct FTagInstance> CharacterTagMatchStartEvents; // 0x838(0x50)
	struct TMap<enum class CharacterRelationBubbleDownVOEnum, struct FTagInstance> CharacterTagBubbleDownEvents; // 0x888(0x50)
	struct TMap<enum class CharacterRelationRoundStartVOEnum, struct FTagInstance> TagCommendRoundStartVO; // 0x8d8(0x50)
	struct TMap<enum class CharacterConvoVOEnum, struct FCharacterRelationshipInstance> CharacterConvoMatchStartVO; // 0x928(0x50)
	float EffortLastPlayedTime; // 0x978(0x04)
	float EffortCooldownSeconds; // 0x97c(0x04)
	struct FTimerHandle HealingReliefVOTimer; // 0x980(0x08)
	struct TMap<enum class DeathMatchVOEnum, struct UAkAudioEvent*> DeathMatchVO; // 0x988(0x50)
	bool HealingOnCooldown; // 0x9d8(0x01)
	bool IsBeingHealed; // 0x9d9(0x01)

	void HasMatchStartDefenderVOLine(struct AShooterCharacter* Character, struct UAudBasePawnVOComponent_C* Base Pawn VO Component, bool& HasLine, struct UAkAudioEvent*& Vo Event, enum class CharacterID& StartingConvoID, struct UAudBasePawnVOComponent_C*& RespondingComponent); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.HasMatchStartDefenderVOLine // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void GetMatchStartDefenderLine(struct AShooterCharacter* Character, bool& HasLine, struct UAkAudioEvent*& Vo Event); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.GetMatchStartDefenderLine // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void GetMatchStartAttackerLine(struct AShooterCharacter* Character, bool& HasLine, struct UAkAudioEvent*& Vo Event); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.GetMatchStartAttackerLine // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void HasMatchStartAttackerVOLine(struct AShooterCharacter* Character, struct UAudBasePawnVOComponent_C* Base Pawn VO Component, bool& HasLine, struct UAkAudioEvent*& Vo Event, enum class CharacterID& StartingConvoID, struct UAudBasePawnVOComponent_C*& RespondingComponent); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.HasMatchStartAttackerVOLine // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_MatchStart_Defenders(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_MatchStart_Defenders // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_MatchStart_Attackers(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_MatchStart_Attackers // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_Ability_CantUse_Cooldown(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_Ability_CantUse_Cooldown // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_Ability_CantUse_Charges(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_Ability_CantUse_Charges // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_DeathMatch_RunnerUp(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_DeathMatch_RunnerUp // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_DeathMatch_MatchWin(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_DeathMatch_MatchWin // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_DeathMatch_OneKillRemaining(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_DeathMatch_OneKillRemaining // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnPostEventCallback(enum class EAkCallbackType CallbackType, struct UAkCallbackInfo* CallbackInfo); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnPostEventCallback // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_BombSpottedDefenderSpawn(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_BombSpottedDefenderSpawn // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_BombSpottedAttackerSpawn(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_BombSpottedAttackerSpawn // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_BombSpottedMid(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_BombSpottedMid // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_BombSpottedC(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_BombSpottedC // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_BombSpottedB(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_BombSpottedB // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_BombSpottedA(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_BombSpottedA // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void UpdateEffortCooldowns(bool& ShouldPlay); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.UpdateEffortCooldowns // (Private|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_MatchStart_ConvoRespond(struct UAkAudioEvent* Vo Event, struct UBaseVOComponent_C* StartConvoVOComp); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_MatchStart_ConvoRespond // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_MatchStart_ConvoStart(struct UAkAudioEvent* Vo Event); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_MatchStart_ConvoStart // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void GetConvoMatchStartResponseVOLine(enum class CharacterID StartingConvoCharID, bool& HasLine, struct UAkAudioEvent*& Vo Event); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.GetConvoMatchStartResponseVOLine // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void HasConvoMatchStartVOLine(struct AShooterCharacter* Character, struct UAudBasePawnVOComponent_C* Base Pawn VO Component, enum class EAresAlliance Alliance, bool& HasLine, struct UAkAudioEvent*& Vo Event, enum class CharacterID& StartingConvoID, struct UAudBasePawnVOComponent_C*& RespondingComponent); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.HasConvoMatchStartVOLine // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void GetConvoMatchStartVOLine(struct AShooterCharacter* Character, enum class EAresAlliance Alliance, struct UAkAudioEvent*& VOLine, bool& VOLineBool, enum class CharacterID& StartingConvoCharID, struct UAudBasePawnVOComponent_C*& RespondingComponent); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.GetConvoMatchStartVOLine // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void HasCommendTagRoundStartVOLine(struct AShooterCharacter* Character, struct UAudBasePawnVOComponent_C* Base Pawn VO Component, bool& HasLine, struct UAkAudioEvent*& Vo Event); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.HasCommendTagRoundStartVOLine // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void GetTagCommendRoundStartVOLine(struct AShooterCharacter* Character, struct UAkAudioEvent*& VOLine, bool& VOLineBool); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.GetTagCommendRoundStartVOLine // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_RoundStart_Tag_Commend(struct UAkAudioEvent* VOEvent); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_RoundStart_Tag_Commend // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void HasTagBubbleDownVOLine(struct AShooterCharacter* Character, enum class CharacterRelationBubbleDownVOEnum CharacterEvent, struct UAudBasePawnVOComponent_C* Base Pawn VO Component, enum class EAresAlliance Alliance, bool& HasLine, struct UAkAudioEvent*& Vo Event); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.HasTagBubbleDownVOLine // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void GetTagBubbleDownVOLine(struct AShooterCharacter* Character, enum class CharacterRelationBubbleDownVOEnum Event, enum class EAresAlliance Alliance, struct UAkAudioEvent*& VOLine, bool& VOLineBool); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.GetTagBubbleDownVOLine // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_BubbleDownTag(struct UAkAudioEvent* Tag Bubble Down Event); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_BubbleDownTag // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void GetTagMatchStartVOLine(struct AShooterCharacter* Character, enum class CharacterRelationMatchVOEnum Event, enum class EAresAlliance Alliance, struct UAkAudioEvent*& VOLine, bool& VOLineBool); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.GetTagMatchStartVOLine // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void HasTagMatchStartVOLine(struct AShooterCharacter* Character, enum class CharacterRelationMatchVOEnum CharacterEvent, struct UAudBasePawnVOComponent_C* Base Pawn VO Component, enum class EAresAlliance Alliance, bool& HasLine, struct UAkAudioEvent*& Vo Event); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.HasTagMatchStartVOLine // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_MatchStart_Tag(struct UAkAudioEvent* Event); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_MatchStart_Tag // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_TagLastKill(struct UAkAudioEvent* Vo Event); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_TagLastKill // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void GetTagLastKillVOLine(struct AShooterCharacter* Victim, struct UAkAudioEvent*& VOLine, bool& VOLine Bool); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.GetTagLastKillVOLine // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void HasTagLastKillVOLine(struct UAudBasePawnVOComponent_C* Base Pawn VO Component, struct AShooterCharacter* Victim, bool& HasLine, struct UAkAudioEvent*& Vo Event); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.HasTagLastKillVOLine // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_RoundStart_Tags_Enemy(struct UAkAudioEvent* Vo Event); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_RoundStart_Tags_Enemy // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_TagKill(struct UDamageResponse* DamageResponse, struct UAkAudioEvent* VOEvent); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_TagKill // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void HasTagKillVOLine(struct UAudBasePawnVOComponent_C* Base Pawn VO Component, struct AShooterCharacter* Victim, bool& HasLine, struct UAkAudioEvent*& Vo Event); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.HasTagKillVOLine // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void GetTagKillVOLine(struct AShooterCharacter* Victim, struct UAkAudioEvent*& VOLine, bool& VOLine Bool); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.GetTagKillVOLine // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void HasCharacterRoundStartTagVOLine(struct AShooterCharacter* Character, struct UAudBasePawnVOComponent_C* Base Pawn VO Component, enum class TagAllianceVOEnum Event, enum class EAresAlliance Alliance, bool& HasLine, struct UAkAudioEvent*& Vo Event, struct AShooterCharacter*& SpokenToTagChar); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.HasCharacterRoundStartTagVOLine // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void GetCharacterRoundStartTagVOLine(struct AShooterCharacter* Character, enum class TagAllianceVOEnum Event, enum class EAresAlliance Alliance, struct UAkAudioEvent*& VOLine, bool& VOLineBool, struct AShooterCharacter*& SpokenToTagChar); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.GetCharacterRoundStartTagVOLine // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_RoundStart_Tags_Ally(struct UAkAudioEvent* Vo Event); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_RoundStart_Tags_Ally // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_RoundEnd(enum class RoundEndVOEnum Key); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_RoundEnd // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	bool HasGameplayEffect(struct UObject* Object, struct UGameplayEffect* EffectDefinition); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.HasGameplayEffect // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3511190
	void FindDamageTypeKills(struct UDamageResponse* DamageResponse, bool& DmgTypeFound, struct UAkAudioEvent*& AK_Event); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.FindDamageTypeKills // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void FindGameplayEffectKills(struct UDamageResponse* DamageResponse, bool& BuffFound, struct UAkAudioEvent*& AK_Event); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.FindGameplayEffectKills // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	bool IsCurrentVOComponent(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.IsCurrentVOComponent // (Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3511190
	void On Auth Char Last Kill(struct UAudBasePawnVOComponent_C* Base Pawn VO Component, struct UDamageType* Damage Type, struct UDamageResponse* Damage Response); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.On Auth Char Last Kill // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void On Auth Char Pentakill(struct UAudBasePawnVOComponent_C* VO Component); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.On Auth Char Pentakill // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void GetCommendRoundStartVOLine(struct AShooterCharacter* Character, struct UAkAudioEvent*& VOLine, bool& VOLineBool); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.GetCommendRoundStartVOLine // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void HasCommendRoundStartVOLine(struct AShooterCharacter* Character, struct UAudBasePawnVOComponent_C* Base Pawn VO Component, bool& HasLine, struct UAkAudioEvent*& Vo Event); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.HasCommendRoundStartVOLine // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_RelationshipKill(struct UDamageResponse* DamageResponse, struct UAkAudioEvent* VOEvent); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_RelationshipKill // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_LastKillMeleeKill(struct UAudBasePawnVOComponent_C* VO Component, struct UDamageType* Damage Type, struct UDamageResponse* Damage Response); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_LastKillMeleeKill // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void GetRelationshipLastKillVOLine(struct AShooterCharacter* Victim, struct UAkAudioEvent*& VOLine, bool& VOLine Bool); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.GetRelationshipLastKillVOLine // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void HasRelationshipLastKillVOLine(struct UAudBasePawnVOComponent_C* Base Pawn VO Component, struct AShooterCharacter* Victim, bool& HasLine, struct UAkAudioEvent*& Vo Event); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.HasRelationshipLastKillVOLine // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void GetMapMatchWinVOLine(struct AShooterCharacter* Character, struct FString MapName, struct UAkAudioEvent*& VOLine, bool& VOLineBool); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.GetMapMatchWinVOLine // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void HasMapMatchWinVOLine(struct AShooterCharacter* Character, struct UAudBasePawnVOComponent_C* Base Pawn VO Component, struct FString MapName, bool& HasLine, struct UAkAudioEvent*& Vo Event); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.HasMapMatchWinVOLine // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_Hold(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_Hold // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_ClearArea(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_ClearArea // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_Push(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_Push // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_Regroup(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_Regroup // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_NeedScouting(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_NeedScouting // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_NeedDisrupt(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_NeedDisrupt // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_NeedVisionBlock(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_NeedVisionBlock // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_BubbleDownCharSpecific(struct UAkAudioEvent* Char Spec Bubble Down Event); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_BubbleDownCharSpecific // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void HasRelationshipBubbleDownVOLine(struct AShooterCharacter* Character, enum class CharacterRelationBubbleDownVOEnum CharacterEvent, struct UAudBasePawnVOComponent_C* Base Pawn VO Component, enum class EAresAlliance Alliance, bool& HasLine, struct UAkAudioEvent*& Vo Event); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.HasRelationshipBubbleDownVOLine // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void GetRelationshipBubbleDownVOLine(struct AShooterCharacter* Character, enum class CharacterRelationBubbleDownVOEnum Event, enum class EAresAlliance Alliance, struct UAkAudioEvent*& VOLine, bool& VOLineBool); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.GetRelationshipBubbleDownVOLine // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void GetRelationshipMatchStartVOLine(struct AShooterCharacter* Character, enum class CharacterRelationMatchVOEnum Event, enum class EAresAlliance Alliance, struct UAkAudioEvent*& VOLine, bool& VOLineBool); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.GetRelationshipMatchStartVOLine // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void HasRelationshipMatchStartVOLine(struct AShooterCharacter* Character, enum class CharacterRelationMatchVOEnum CharacterEvent, struct UAudBasePawnVOComponent_C* Base Pawn VO Component, enum class EAresAlliance Alliance, bool& HasLine, struct UAkAudioEvent*& Vo Event); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.HasRelationshipMatchStartVOLine // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_LastKillVIP(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_LastKillVIP // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void HasRelationshipKillVOLine(struct UAudBasePawnVOComponent_C* Base Pawn VO Component, struct AShooterCharacter* Victim, bool& HasLine, struct UAkAudioEvent*& Vo Event); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.HasRelationshipKillVOLine // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_UltAlmostReady(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_UltAlmostReady // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_Ability_CantUse_Generic(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_Ability_CantUse_Generic // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_UltNotReady_1P_Only(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_UltNotReady_1P_Only // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void GetVOCriticalRequiredRange(float& VO Critical Required Range); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.GetVOCriticalRequiredRange // (Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x3511190
	void HasRelationshipRoundStartVOLine(struct AShooterCharacter* Character, enum class CharacterRelationRoundStartVOEnum CharacterEvent, struct UAudBasePawnVOComponent_C* Base Pawn VO Component, enum class EAresAlliance Alliance, bool& HasLine, struct UAkAudioEvent*& Vo Event, struct AShooterCharacter*& SpokenToChar); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.HasRelationshipRoundStartVOLine // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void GetRelationshipRoundStartVOLine(struct AShooterCharacter* Character, enum class CharacterRelationRoundStartVOEnum Event, enum class EAresAlliance Alliance, struct UAkAudioEvent*& VOLine, bool& VOLineBool, struct AShooterCharacter*& SpokenToChar); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.GetRelationshipRoundStartVOLine // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_RoundStart_Relationship_Commend(struct UAkAudioEvent* VOEvent); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_RoundStart_Relationship_Commend // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_RoundStart_Relationship_Enemy(struct UAkAudioEvent* Vo Event); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_RoundStart_Relationship_Enemy // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_RoundStart_Relationship_Ally(struct UAkAudioEvent* Vo Event); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_RoundStart_Relationship_Ally // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_OutOfAmmo(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_OutOfAmmo // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_DefuseResume(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_DefuseResume // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_MeleeKill(struct UDamageResponse* DamageResponse, struct UDamageType* DamageType, struct UAudBasePawnVOComponent_C* Char VO Component); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_MeleeKill // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_ObjectivePlanted(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_ObjectivePlanted // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_BubbleDownGeneric(bool WaitsOnAnnouncer, struct UAudBasePawnVOComponent_C* VOComponent); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_BubbleDownGeneric // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_TacSystem(enum class VOTacEnum VOTacEnum); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_TacSystem // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_WonGeneric(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_WonGeneric // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_MatchWin_MapSpecific(struct UAkAudioEvent* VOEvent); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_MatchWin_MapSpecific // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_MatchWin_MVP(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_MatchWin_MVP // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_MatchStart_Relationship(struct UAkAudioEvent* Event); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_MatchStart_Relationship // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_OurCarrierKilled(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_OurCarrierKilled // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_IHaveMoney(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_IHaveMoney // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_RoundStartGeneric(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_RoundStartGeneric // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void GetRelationshipEmoteVOLine(struct AShooterCharacter* EmoteTarget, struct UAkAudioEvent*& VOLine); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.GetRelationshipEmoteVOLine // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_LastKillRelationship(struct UAkAudioEvent* RelationshipKillVOLine); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_LastKillRelationship // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void GetRelationshipKillVOLine(struct AShooterCharacter* Victim, struct UAkAudioEvent*& VOLine, bool& VOLine Bool); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.GetRelationshipKillVOLine // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_Ceremony(enum class CeremonyIdentifier Ceremony, struct UAudBasePawnVOComponent_C* Ceremony Single Player, struct UAudBasePawnVOComponent_C* Ceremony Team Player); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_Ceremony // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_Relief(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_Relief // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_Disgust(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_Disgust // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_AnnoyedPain(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_AnnoyedPain // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_HeadshotKill(struct UDamageType* DamageType, struct UDamageResponse* DamageResponse, struct UAudBasePawnVOComponent_C* Char VO Comp); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_HeadshotKill // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_CalloutMid(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_CalloutMid // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_CalloutC(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_CalloutC // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_CalloutB(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_CalloutB // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_CalloutA(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_CalloutA // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_NobodyGrabbedBomb(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_NobodyGrabbedBomb // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_ObjectiveSpotted(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_ObjectiveSpotted // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_EnemyTeamSpotted(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_EnemyTeamSpotted // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_EnemiesSpotted(enum class ECalloutSuperRegion Region); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_EnemiesSpotted // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_EnemySpotted(enum class ECalloutSuperRegion Region); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_EnemySpotted // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_BombSpotted(enum class ECalloutSuperRegion Region); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_BombSpotted // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_UltNotReady(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_UltNotReady // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_UltReady(bool PlayToAllies); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_UltReady // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_RushThem(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_RushThem // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_PlayForPicks(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_PlayForPicks // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_NeedDrop(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_NeedDrop // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_Saving(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_Saving // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_Buying(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_Buying // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_GoingMid(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_GoingMid // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_GoingC(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_GoingC // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_GoingB(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_GoingB // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_GoingA(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_GoingA // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_FallBack(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_FallBack // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_TakePoint(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_TakePoint // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_LetRotate(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_LetRotate // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_Rotating(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_Rotating // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_NeedHealing(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_NeedHealing // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_BarelySurvived(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_BarelySurvived // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_Killstreak(int32_t KillstreakCount, struct UDamageResponse* Damage Response, struct UDamageType* Damage Type, struct UAudBasePawnVOComponent_C* CharVOComp); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_Killstreak // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_LastRoundOfHalfAsDefenders(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_LastRoundOfHalfAsDefenders // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_LastRoundOfHalfAsAttackers(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_LastRoundOfHalfAsAttackers // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_WonComingBack(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_WonComingBack // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_MatchStart_MapSpecfic(struct FString Map Name, bool& NoMapLine); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_MatchStart_MapSpecfic // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_Quiet(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_Quiet // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_OnMyWay(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_OnMyWay // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_TakeDamage_EnemyFeedback(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_TakeDamage_EnemyFeedback // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void ShouldPlayImmediately(enum class VOPriorityEnum Priority, float TimeEnteredQueue, float QueueTimeout, bool WaitsOnAnnouncer, struct UBaseVOComponent_C* WaitOnCharacter, bool& Immediately); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.ShouldPlayImmediately // (Protected|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure|Const) // @ game+0x3511190
	void OnAuth_Char_Death(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_Death // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void UpdateEmoteCooldowns(bool& ShouldPlay); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.UpdateEmoteCooldowns // (Private|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_Cough(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_Cough // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_AbilityXEquip(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_AbilityXEquip // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_BubbleDownGameState(struct TArray<struct FAkSwitch>& Bubble Down Ak Switches); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_BubbleDownGameState // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_ObjectiveDropped(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_ObjectiveDropped // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_EmoteSystem(enum class VOEmoteEnum VOEmoteEnum); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_EmoteSystem // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_MatchStart(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_MatchStart // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_MatchWin(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_MatchWin // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_GrenadeCast(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_GrenadeCast // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_AbilityXCast(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_AbilityXCast // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_AbilityECast(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_AbilityECast // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_AbilityQCast(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_AbilityQCast // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_GamePointWin(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_GamePointWin // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_ObjectiveDefused(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_ObjectiveDefused // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_DefuseOutofTime(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_DefuseOutofTime // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_ObjectivePickedUp(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_ObjectivePickedUp // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_Kill(struct UDamageResponse* DamageResponse, struct UDamageType* DamageType, struct UAudBasePawnVOComponent_C* Char VO Component); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_Kill // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_Reloading(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_Reloading // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_CantUse(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_CantUse // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_WonDoingGreat(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_WonDoingGreat // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_TakeDamage(float Fall Distance, float Damage Taken); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_TakeDamage // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnAuth_Char_Ressurected(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnAuth_Char_Ressurected // (Public|BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void GetBasePawn(struct ABasePawn_C*& Base Pawn); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.GetBasePawn // (Private|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure|Const) // @ game+0x3511190
	void OnTakeAnyDamage_Event_1(struct AActor* DamagedActor, float Damage, struct UDamageType* DamageType, struct AController* InstigatedBy, struct AActor* DamageCauser); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnTakeAnyDamage_Event_1 // (BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void AuthOnCharacterResurrected_Event_1(struct AOwnerExclusivePlayerInfo* Resurrector); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.AuthOnCharacterResurrected_Event_1 // (BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void CustomEvent_1(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.CustomEvent_1 // (BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void ReceiveBeginPlay(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.ReceiveBeginPlay // (Event|Public|BlueprintEvent) // @ game+0x3511190
	void PlayHealingReliefVO(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.PlayHealingReliefVO // (BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void ResetReliefEffort(); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.ResetReliefEffort // (BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void HealTagUpdate(struct UAresAbilitySystemComponent* AbilitySystem, struct FGameplayTag Tag, bool TagActive); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.HealTagUpdate // (BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void OnCharacterPreDeath_Event_1(struct AShooterCharacter* Character, struct APawn* KillerPawn); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.OnCharacterPreDeath_Event_1 // (BlueprintCallable|BlueprintEvent) // @ game+0x3511190
	void ExecuteUbergraph_AudBasePawnVOComponent(int32_t EntryPoint); // Function AudBasePawnVOComponent.AudBasePawnVOComponent_C.ExecuteUbergraph_AudBasePawnVOComponent // (Final|UbergraphFunction|HasDefaults) // @ game+0x3511190
};

